import { Button, Container, Image, Text, useColorMode } from "@chakra-ui/react";
import Head from "next/head";
import { Card } from "../components/Card";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Button onClick={toggleColorMode}>Test Me</Button>
          <Card>
            <Image
              src="https://thispersondoesnotexist.com/image"
              h={120}
              w={120}
              borderRadius="full"
            />
            <Text as="h2">Jordan McDonough</Text>
          </Card>
        </Container>
      </main>
    </div>
  );
}
