import { Button, Container } from "@chakra-ui/react";
import Head from "next/head";
import { Card } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Button>Test Me</Button>
          <Card>Hello</Card>
        </Container>
      </main>
    </div>
  );
}
